name: GitHub Metrics (compact)
on:
  schedule: [{ cron: "30 0 * * *" }]   # daily
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # REQUIRED
          token: ${{ secrets.METRICS_TOKEN }}   # PAT with: repo, read:org
          user: Mohammad7Abubakar
          filename: metrics-compact.svg
          config_timezone: Asia/Karachi
          template: classic

          # keep base lean
          base: header, repositories
          repositories_affiliations: owner, collaborator, organization_member

          # languages (compact)
          plugin_languages: yes
          plugin_languages_limit: 6
          plugin_languages_details: percentage
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_followup: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: user
          plugin_achievements: yes

          # turn OFF the noisy stuff
          plugin_stargazers: no
          plugin_followers: no
          plugin_habits: no
          plugin_activity: no

          extras_css: |
            /* Title / section headings */
            .heading, .title, h1, h2 { fill:#64ffda !important; color:#64ffda !important; }
            /* Body text */
            text, .field, .label, .value { fill:#e5e7eb !important; color:#e5e7eb !important; }
            /* Hide bits you don't want to see */
            .sponsors, .packages, .releases, .watchers { display:none !important; }
            /* Optional: tighter spacing */
            .row { margin-top: 6px !important; margin-bottom: 6px !important; }